In [ ]:
import numpy as np

**Max pooling**

In [ ]:
a = np.array([[29,15,28,184],
               [0,100,70,38],
               [12,12,7,2],
              [12,12,45,6]])

a1 = a[:2,:2].max()
a2 = a[:2,2:].max()
a3 = a[2:,:2].max()
a4 = a[2:,2:].max()

print('Original',a,sep='\n')
print('\nCon max Pooling', np.array([[a1,a2],
                [a3,a4]]),sep='\n')


Original
[[ 29  15  28 184]
 [  0 100  70  38]
 [ 12  12   7   2]
 [ 12  12  45   6]]

Con max Pooling
[[100 184]
 [ 12  45]]


**Average Pooling**

In [ ]:
a = np.array([[29,15,28,184],
               [0,100,70,38],
               [12,12,7,2],
              [12,12,45,6]])

a1 = a[:2,:2].mean()
a2 = a[:2,2:].mean()
a3 = a[2:,:2].mean()
a4 = a[2:,2:].mean()

print('Original',a,sep='\n')
print('\nCon average Pooling',np.array([[a1,a2],
                [a3,a4]]),sep='\n')

Original
[[ 29  15  28 184]
 [  0 100  70  38]
 [ 12  12   7   2]
 [ 12  12  45   6]]

Con average Pooling
[[36. 80.]
 [12. 15.]]
